AWSTemplateFormatVersion: '2010-09-09'
Description: Container Service SQS Queues

Parameters:
  ProductName:
    Type: String
    Description: The service name
  Env:
    Type: String
    Description: The environment name. e.g. dev, prod

Resources:

  MoneySqs:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "MoneySqs-${ProductName}-${Env}.fifo"
      FifoQueue: True
      Tags:
        - Key: Product
          Value: !Ref ProductName
        - Key: Env
          Value: !Ref Env

Outputs:
  MoneySqs:
    Value: !Ref MoneySqs
    Export:
      Name: !Sub "MoneySqs-${ProductName}-${Env}" 