AWSTemplateFormatVersion: 2010-09-09
Description: Dummy services task with 1 parameter
Parameters:
  ProductName:
    Type: String
    Description: The product name
  Env:
    Type: String
    Description: "The environment name. e.g. dev, prod"
    Default: test
  ServiceName:
    Type: String
    Description: The service name
    Default: service    
  DockerImgVersion:
    Type: String
    Description: The version for the image. It comes from the Github Project
    Default: latest        
Resources:
  InvoiceValidateService:
    Type: "AWS::ECS::Service"
    Properties:
      # ServiceName: Fn::Sub: "${ProductName}-${ServiceName}"
      ServiceName: !Sub "${ProductName}-${ServiceName}"      
      Cluster:
        "deref-ecs-fargate-cluster-ECSCluster-Z7IHPQJ14CBG"
      LaunchType: FARGATE
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 75
      DesiredCount: 2
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - "sg-0c456cfba268f5fde"
          Subnets:
            - "subnet-0c67191657be66a67"
            - "subnet-098f71c7edabcc76a"
      TaskDefinition: !Ref LoanDummyDemoDefinition
  LoanDummyDemoDefinition:
    Type: "AWS::ECS::TaskDefinition"
    Properties:
      Family: !Sub "${ProductName}-${ServiceName}"
      Cpu: 512
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn:
        "arn:aws:iam::085980086235:role/deref-ecs-fargate-cluster-ECSTaskExecutionRole-14H35CB2DJ016"
      ContainerDefinitions:
        - Name: ui-code
          MemoryReservation: 32
          Image: !Sub "${DockerImgVersion}"
          Cpu: 0
          Essential: true
          Environment:
            - Name: APP_ENV
              Value: prod
          PortMappings:
            - Protocol: tcp
              ContainerPort: 80
              HostPort: 80              
          Secrets:
            - Name: DATABASE_URL
              ValueFrom: !Sub >-
                arn:aws:secretsmanager:ap-southeast-2:085980086235:secret:DATABASE_URL-ei1vF9
